// This file will be dynamically generated by the run-with-ngrok.sh script
// Default fallback configuration
window.API_URL = "http://localhost:5000/api";
console.log("Using default API URL. This file should be replaced with the actual ngrok URL when running in production.");