// This file will be dynamically generated by the run-with-ngrok.sh script
// Default fallback configuration
window.API_URL = "https://d86c-146-196-32-136.ngrok-free.app/api";
console.log("API URL set to: " + window.API_URL);